spring:
  profiles:
    active: dev
server:
  port: 8228
app:
  name: actionAgent
  description: ${app.name} with Spring Boot boosted.

---
spring:
  profiles: dev
kafka:
  consumer:
    zookeeper:
      connect: localhost:32028
    servers: localhost:31090,localhost:31091,localhost:31092
    enable:
      auto:
        commit: true
    session:
      timeout: 6000
    auto:
      commit:
        interval: 100
      offset:
        reset: latest
    topic: action
    group:
      id: test
    concurrency: 10
  producer:
    servers: localhost:31090,localhost:31091,localhost:31092
    retries: 0
    batch:
      size: 4096
    linger: 1
    topic: report
    buffer:
      memory: 40960

