spring:
  profiles:
    active: prod
server:
  port: 8228
app:
  name: actionAgent
  description: ${app.name} with Spring Boot boosted.
logging:
  level:
    org.springframework.web: INFO
#    org.apache.kafka: WARN
#    org.springframework.kafka.listener: WARN
  file:
    name: logs/airgent.log
    path: logs

---
spring:
  profiles: test
kafka:
  consumer:
    zookeeper:
      connect: 40.117.113.67:2181
    servers: 40.117.113.67:9092
    enable:
      auto:
        commit: true
    session:
      timeout: 6000
    auto:
      commit:
        interval: 100
      offset:
        reset: latest
    topic: testaction
    group:
      id: test2
    concurrency: 10
  producer:
    servers: 40.117.113.67:9092
    retries: 0
    batch:
      size: 4096
    linger: 1
    topic: report
    buffer:
      memory: 40960
agent:
  init: false

---
spring:
  profiles: local
kafka:
  consumer:
    zookeeper:
      connect: 40.117.113.67:2181
    servers: 40.117.113.67:9092
    enable:
      auto:
        commit: true
    session:
      timeout: 6000
    auto:
      commit:
        interval: 100
      offset:
        reset: latest
    topic: action
    group:
      id: test2
    concurrency: 10
  producer:
    servers: 40.117.113.67:9092
    retries: 0
    batch:
      size: 4096
    linger: 1
    topic: report
    buffer:
      memory: 40960
agent:
  init: true

---
spring:
  profiles: prod
kafka:
  consumer:
    zookeeper:
      connect: 40.117.113.67:2181
    servers: 40.117.113.67:9092
    enable:
      auto:
        commit: true
    session:
      timeout: 6000
    auto:
      commit:
        interval: 100
      offset:
        reset: latest
    topic: action
    group:
      id: test2
    concurrency: 1
  producer:
    servers: 40.117.113.67:9092
    retries: 0
    batch:
      size: 4096
    linger: 1
    topic: report
    buffer:
      memory: 40960
agent:
  init: true