FROM airta/agent_base_0_platform:{{ versionPlaceHolder }}
LABEL authors="Allen Yin <yinxinla@163.com>"

USER root

#==============
# Xvfb
#==============
RUN apt-get update -qqy \
  && apt-get -qqy install \
    fluxbox \
    fonts-liberation \
    fonts-ipafont-gothic \
    fonts-wqy-zenhei \
    fonts-tlwg-loma-otf \
    libfontconfig \
    libfreetype6 \
    ttf-ubuntu-font-family \
    x11vnc \
    xvfb \
    xfonts-cyrillic \
    xfonts-scalable \
  && rm -rf /var/lib/apt/lists/* /var/cache/apt/* \
  && apt-get -qyy clean
  && mkdir -p /home/airbot/.vnc \
  && x11vnc -storepasswd secret /home/airbot/.vnc/passwd \
  && chown -R airbot:airbot /home/airbot/

#==============================
# Locale and encoding settings
#==============================
ENV LANG_WHICH en
ENV LANG_WHERE US
ENV ENCODING UTF-8
ENV LANGUAGE ${LANG_WHICH}_${LANG_WHERE}.${ENCODING}
ENV LANG ${LANGUAGE}

#============================
# Some configuration options
#============================
ENV SCREEN_WIDTH 1360
ENV SCREEN_HEIGHT 1020
ENV SCREEN_DEPTH 24
ENV SCREEN_DPI 96
ENV DISPLAY :99.0
ENV START_XVFB true

#========================
# GRAPH Configuration
#========================
# As integer, maps to "maxInstances"
ENV NODE_MAX_INSTANCES 1
# As integer, maps to "maxSession"
ENV NODE_MAX_SESSION 1
# As address, maps to "host"
ENV NODE_HOST 0.0.0.0

# Following line fixes https://github.com/SeleniumHQ/docker-selenium/issues/87
ENV DBUS_SESSION_BUS_ADDRESS=/dev/null

# Layer size: small: ~9 MB
# Layer size: small: ~9 MB MB (with --no-install-recommends)
RUN locale-gen ${LANGUAGE} \
  && dpkg-reconfigure --frontend noninteractive locales

#===================================================
# Run the following commands as non-privileged user
#===================================================

USER airbot

#==============================
# Scripts to run Selenium Node and XVFB
#==============================
COPY start-xvfb.sh \
     functions.sh \
      /opt/bin/

#==============================
# Supervisor configuration file
#==============================
COPY graph.conf /etc/supervisor/conf.d/
RUN sudo chmod +x /opt/bin/start-xvfb.sh \
    && sudo chmod +x /opt/bin/functions.sh \
    && sudo mkdir -p /tmp/.X11-unix \
    && sudo chmod 1777 /tmp/.X11-unix
